### Register Admin
POST http://localhost:5000/admin-api/register
Content-Type: application/json

{
    "name":"Admin",
    "email":"admin@gmail.com",
    "password":"admin123"
}



### Admin Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin123"
}



### Get Admin Dashboard
GET http://localhost:5000/admin-api/dashboard
Authorization: Bearer your_jwt_token