### Admin Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin123"
}



### Doctor Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"doctor@gmail.com",
    "password":"doctor123"
}



### Patient Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"ananya@gmail.com",
    "password":"ananya123"
}



### Verify Token
GET http://localhost:5000/auth/verify
Authorization: Bearer your_jwt_token