### Register Patient
POST http://localhost:5000/patient-api/register
Content-Type: application/json

{
    "name":"Sai Ananya",
    "email":"ananya@gmail.com",
    "password":"ananya123",
    "age":20,
    "gender":"Female",
    "bloodGroup":"O+",
    "phone":"9876543210",
    "address":"Hyderabad",
    "medicalHistory":[
        {
            "disease":"Fever",
            "diagnosisDate":"2026-05-01",
            "notes":"Recovered"
        }
    ]
}



### Patient Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"ananya@gmail.com",
    "password":"ananya123"
}



### Get All Patients
GET http://localhost:5000/patient-api/patients
Authorization: Bearer your_jwt_token



### Get Patient By ID
GET http://localhost:5000/patient-api/patient/patient_id
Authorization: Bearer your_jwt_token



### Update Patient
PUT http://localhost:5000/patient-api/update-patient/patient_id
Authorization: Bearer your_jwt_token
Content-Type: application/json

{
    "phone":"9999999999",
    "address":"Bangalore"
}



### Delete Patient
DELETE http://localhost:5000/patient-api/delete-patient/patient_id
Authorization: Bearer your_jwt_token



### Search Patients
GET http://localhost:5000/patient-api/search/ananya
Authorization: Bearer your_jwt_token